######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 2 00:00:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# CONFIG += debug

# Input
HEADERS += base.h mainwin.h \
    filetypes.h
FORMS += mainwin.ui replace.ui \
    replace.ui
SOURCES += main.cpp mainwin.cpp \
    snx.cpp \
    ks.cpp \
    srp.cpp
RESOURCES += resources.qrc
